image: atlassian/default-image:2

pipelines:
  branches:
    feature/*:
      - step:
          name: Test
          image:
            name: 555393537168.dkr.ecr.eu-west-1.amazonaws.com/build-tools/aws-sam-cli:latest
            aws:
              access-key: $AWS_ACCESS_KEY_ID_UAT
              secret-key: $AWS_SECRET_ACCESS_KEY_UAT
          services:
            - docker
          script:
            - make ci-test

    develop:
      - step:
          name: Test
          image:
            name: 555393537168.dkr.ecr.eu-west-1.amazonaws.com/build-tools/aws-sam-cli:latest
            aws:
              access-key: $AWS_ACCESS_KEY_ID_UAT
              secret-key: $AWS_SECRET_ACCESS_KEY_UAT
          services:
            - docker
          script:
            - make ci-test
