AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy automation for Enzek Meterpoint Readings DAGs

Parameters:
  Environment:
    Type: String
    Default: uat
    AllowedValues:
      - uat
      - staging
      - prod
  StackName:
    Type: String
    Default: enzek-meterpoint-readings

Mappings:
  EnvironmentMap:
    uat:
      SentryDsn: AWS::NoValue
    staging:
      SentryDsn: AWS::NoValue
    prod:
      SentryDsn: AWS::NoValue


Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub enzek-meterpoint-readings-artifacts-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: category
          Value: cdw
        - Key: environment
          Value: !Ref Environment

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${ArtifactBucket}
              - !Sub arn:aws:s3:::${ArtifactBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/ci-agent

  DeployFnSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${StackName}-DeployFnSecurityGroup
      VpcId: !ImportValue CoreVPC
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: name
          Value: !Sub ${StackName}-DeployFnSecurityGroup
        - Key: category
          Value: cdw

  DeployFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${StackName}-DeployFn
      CodeUri: deploy-fn/
      Handler: deploy.lambda_handler
      Runtime: python3.7
      Timeout: 15
      Events:
        ArtifactUploaded:
          Type: S3
          Properties:
            Bucket:
              Ref: ArtifactBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix      # or "suffix"
                  Value: enzek-meterpoint-readings
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt DeployFnSecurityGroup.GroupId
        SubnetIds: !Split [ ",", !ImportValue CorePrivateSubnets ]
